version: '2'

services:
    promysql:
       build: 
            context: .
            dockerfile: DockerfileMySQL
       tty: true
    prozab-serv:
        build: 
            context: .
            dockerfile: DockerfileZab-Serv
        ports:
            - "8083:80"
        links:
            - promysql:mysql
        tty: true
    prozab-agent:
        build: 
            context: .
            dockerfile: DockerfileZab-Agent
        tty: true
        links:
            - prozab-serv:serv
    proucd-serv:
        build: 
            context: .
            dockerfile: DockerfileUCD-Serv
        ports:
            - "8084:8443"
        links:
            - promysql:mysql
        tty: true
    proucd-agent:
        build: 
            context: .
            dockerfile: DockerfileUCD-Agent
        links:
            - proucd-serv:serv
        tty: true
