FROM ubuntu
MAINTAINER Sam Irvine

RUN apt-get update -y
RUN apt-get install -y nano

RUN apt-get install -y graphite-web graphite-carbon
#RUN apt-get install -y postgresql libpq-dev python-psycopg2

ENTRYPOINT bash
